### PR TITLE
Feature/gme downloader

### PR DESCRIPTION
**Pull request by CremaLuca**
## Premise
We have to download data from GME right? There are three ways:
1) Hand pick dates to download and do it by hand for every category on the downloads page.
2) Require access to FTP by ending an irl mail to Rome and get credentials back by irl mail.
3) Somehow hack the web pages to let them think you're a human pressing buttons.
Here we are having a look at how I implemented 3.

## Changes

Created `GMEDownloader` class, the main method is `get_data` that is responsible for everything else.
The class doesn't have attributes or anything so it could actually be just a module, but I preferred to keep it organized.

### get_data method

Uses python requests library to create a session (could have avoided using a session because there are no cookies actually, but might be useful for future edits (?)) and then creates an HTTP POST request with fake form data saying "yes I accept" twice so that their system is tricked to think the terms of use acceptance form has been filled correctly.
`_VIEWSTATE` and `__EVENTVALIDATION` are required for the trick to work, the value of those two keys has been found in deep research in the network page of my browser and they were kinda the same so I hope they'll be ok on other computers too.

`DICTIONARY` contains all possible data this class is able to extract from the website.

If data hasn't been found or there has been an error (status code != 200) it raises a ValueError (stole it from alpha vantage).

### Warning

This class is not meant to create files, I'd like to move that kind of functions to another class in common with YahooFinance downloader and AphaVantage downloader

That's it.
Have fun.

### CODE REVIEW

**Comment by CremaLuca** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- gme_downloader.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OTRI-Unipd/history-downloader/pullRequest?prid=5365914&bid=17583142)

**Comment by CremaLuca** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- gme_downloader.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OTRI-Unipd/history-downloader/pullRequest?prid=5365914&bid=17583142)

**Review by ricdezen — APPROVED** [review]
Nothing to really complain about.
I'd maybe move `DICTIONARY `to a separate file.

**Comment by CremaLuca** [comment]
Sure, moved the dictionary into a json file

**Pull request merged**
